#pragma once
#include <game/match_instance.hpp>
#include <common/lobby.hpp>
#include <common/ws.hpp>
#include <atomic>
#include <string>
#include <unordered_map>
#include <App.h>
#include <action_router.hpp>
#include <websocket_context.hpp>
#include <webserver.hpp>

/**
 * @file lobby_controller.hpp
 * @brief Definition of the controller for managing Lobbies. Handles all the I/O between
 * Client and Server regarding the initialization of Lobbies, and the start of game Matches,
 * to which it subsequently hands over control.
 */

/**
 * @typedef GameStartedCallback
 * @brief Callback invoked when a match starts.
 * @tag LOBBY-TYP-001
 */
using GameStartedCallback = std::function<void(Lobby*)>;

/**
 * @typedef PlayerReplacedCallback
 * @brief Callback invoked when a player is replaced (e.g. by a bot).
 * @tag LOBBY-TYP-002
 */
using PlayerReplacedCallback = std::function<void(Lobby*)>;

/**
 * @class LobbyController
 * @brief Manages the in-memory state of all the active lobbies.
 * * This class does not use a database: the lobbies are ephemeral and live only
 * for the duration of the server session. It handles creation, joining,
 * temporary disconnections and reconnection of clients via WebSocket.
 * * @tag LOBBY-CTRL-000
 */
class LobbyController {
public:
    /**
     * @brief Constructor of the LobbyController.
     * Registers the WebSocket action handlers on the provided router.
     * Keeps a reference to `app` for pub/sub broadcasts and the eviction timer.
     * * @param webserver Reference to the main WebServer.
     * @tag LOBBY-CTRL-001
     */
    LobbyController(WebServer& webserver);

    /**
     * @brief Destructor. Takes care of cleaning up the associated libuv timers.
     * @tag LOBBY-CTRL-002
     */
    ~LobbyController();

    /**
     * @brief Handler called when a client establishes a new WebSocket connection.
     * If the user was already in a lobby (reconnection scenario), it updates the socket
     * pointer and restores their presence.
     * * @param ws Pointer to the WebSocket socket.
     * @param sd Data associated with the socket (contains username, etc.).
     * @tag LOBBY-CTRL-003
     */
    void OnOpen(AppWebSocket* ws, PerSocketData* sd);

    /**
     * @brief Handler called when a client closes the connection.
     * Marks the member as disconnected and records the timestamp. Does not immediately remove
     * the user, but starts a grace period.
     * * @param ws Pointer to the disconnected WebSocket socket.
     * @param sd Data associated with the socket.
     * @tag LOBBY-CTRL-004
     */
    void OnClose(AppWebSocket* ws, PerSocketData* sd);

    /**
     * @brief Retrieves a pointer to a lobby by its invite code.
     * * @param code 6-character alphanumeric code (e.g. "XK4F9Z").
     * @return Lobby* Pointer to the lobby, or nullptr if not found.
     * @tag LOBBY-CTRL-005
     */
    Lobby* GetLobbyByCode(const std::string& code) {
        auto it = code_to_id_.find(code);
        if (it != code_to_id_.end()) {
            return &lobbies_.at(it->second);
        }
        return nullptr;
    }

    /**
     * @brief Retrieves a pointer to a lobby by its internal numeric ID.
     * * @param id Unique ID generated by the server.
     * @return Lobby* Pointer to the lobby, or nullptr if not found.
     * @tag LOBBY-CTRL-006
     */
    Lobby* GetLobbyById(const uint32_t id) {
        auto it = lobbies_.find(id);
        if (it != lobbies_.end()) {
            return &it->second;
        }
        return nullptr;
    }

    /**
     * @brief Registers a callback to execute when a match starts.
     * @param callback The function to invoke.
     * @tag LOBBY-CTRL-007
     */
    void OnGameStarted(GameStartedCallback callback) {
        game_started_callback_ = std::move(callback);
    }

    /**
     * @brief Registers a callback to execute when a player is replaced.
     * @param callback The function to invoke.
     * @tag LOBBY-CTRL-008
     */
    void OnPlayerReplaced(PlayerReplacedCallback callback) {
        player_replaced_callback_ = std::move(callback);
    }

    /**
     * @brief Saves the current state of the match associated with the lobby to the database.
     * @param lobby Reference to the lobby whose state to save.
     * @tag LOBBY-CTRL-009
     */
    void SaveMatchStateToDB(Lobby& lobby);

    /**
     * @brief Grace period before a disconnected user is evicted.
     * @tag LOBBY-CFG-001
     */
    static constexpr int kReconnectGraceMs = 1'000 * 30;

    /**
     * @brief Maximum number of players allowed in a single lobby.
     * @tag LOBBY-CFG-002
     */
    static constexpr int kMaxMembers = 4;

private:
    /**
     * @brief Synchronizes the state of the bots within the lobby.
     * @param lobby The lobby to update.
     * @tag LOBBY-PRIV-001
     */
    void SyncBots(Lobby& lobby);

    /**
     * @brief Verifies the integrity of the current match data (e.g. host realignment).
     * @param lobby The lobby to verify.
     * @tag LOBBY-PRIV-002
     */
    void CheckMatchIntegrity(Lobby& lobby);

    /**
     * @brief Handles the request to create a new lobby.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     * @tag LOBBY-ACT-001
     */
    void HandleCreate(WsContext ctx, const json& msg);

    /**
     * @brief Handles the request to join a lobby via code.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     * @tag LOBBY-ACT-002
     */
    void HandleJoin(WsContext ctx, const json& msg);

    /**
     * @brief Handles the request to reconnect to a lobby.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     * @tag LOBBY-ACT-003
     */
    void HandleRejoin(WsContext ctx, const json& msg);

    /**
     * @brief Handles a user's voluntary departure from the lobby.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     * @tag LOBBY-ACT-004
     */
    void HandleLeave(WsContext ctx, const json& msg);

    /**
     * @brief Handles the request for the list of active public lobbies.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     * @tag LOBBY-ACT-005
     */
    void HandleList(WsContext ctx, const json& msg);

    /**
     * @brief Promotes a specific player to the Host role of the lobby.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     * @tag LOBBY-ACT-006
     */
    void HandlePromote(WsContext ctx, const json& msg);

    /**
     * @brief Kicks a player from the lobby (only executable by the Host).
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     * @tag LOBBY-ACT-007
     */
    void HandleKick(WsContext ctx, const json& msg);

    /**
     * @brief Updates the lobby settings (only executable by the Host).
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     * @tag LOBBY-ACT-008
     */
    void HandleUpdateSettings(WsContext ctx, const json& msg);

    /**
     * @brief Requests the list of previously saved matches.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     * @tag LOBBY-ACT-009
     */
    void HandleGetSavedMatchesList(WsContext ctx, const json& msg);

    /**
     * @brief Resumes a saved match from its ID.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     * @tag LOBBY-ACT-010
     */
    void HandleResumeSavedMatch(WsContext ctx, const json& msg);

    /**
     * @brief Permanently deletes a saved match from the DB.
     * @param ctx WebSocket context of the request.
     * @param msg Associated JSON payload.
     * @tag LOBBY-ACT-011
     */
    void HandleDeleteSavedMatch(WsContext ctx, const json& msg);

    /**
     * @brief Starts the match for the current lobby. Initializes the game instance.
     * @param context WebSocket context of the request.
     * @param message Associated JSON payload.
     * @tag LOBBY-ACT-012
     */
    void HandleStartGame(WsContext context, const nlohmann::json& message);

    /**
     * @brief Generates a unique 6-character alphanumeric code (Invite Code).
     * @return std::string The generated invite code.
     * @tag LOBBY-UTIL-001
     */
    static std::string GenerateInviteCode();

    /**
     * @brief Serializes the member list into JSON format for sending via WebSocket.
     * @param lobby The lobby whose members to serialize.
     * @return json JSON object representing the members.
     * @tag LOBBY-UTIL-002
     */
    static json MemberListJson(const Lobby& lobby);

    /**
     * @brief Broadcasts the `lobby_updated` event to all connected members.
     * @param lobby The lobby to broadcast from.
     * @tag LOBBY-UTIL-003
     */
    void BroadcastUpdate(const Lobby& lobby) const;

    /**
     * @brief Removes a member from the lobby. Destroys the lobby if it becomes empty.
     * @param lobby_id ID of the lobby.
     * @param username Username of the player to remove.
     * @param explicit_leave True if the user left voluntarily.
     * @param request_id ID of the request (optional, for tracking).
     * @return true if the lobby still exists, false if it was destroyed.
     * @tag LOBBY-PRIV-003
     */
    bool RemoveMember(uint32_t lobby_id, const string& username, bool explicit_leave = true, const string& request_id = "");

    /**
     * @brief Finds which lobby a given user currently belongs to.
     * @param username The username to look up.
     * @return Lobby* Pointer to the lobby, nullptr if not in any lobby.
     * @tag LOBBY-PRIV-004
     */
    Lobby* FindLobbyForUser(const std::string& username);

    GameStartedCallback game_started_callback_;     /**< Callback for match start. */
    PlayerReplacedCallback player_replaced_callback_;/**< Callback for player replacement. */

    ActionRouter& action_router_;                   /**< Reference to the WS action router. */
    uWS::SSLApp& app_;                              /**< Reference to the uWebSockets instance. */

    std::unordered_map<uint32_t, Lobby> lobbies_;   /**< Primary storage of the lobbies. */
    std::unordered_map<std::string, uint32_t> code_to_id_; /**< Secondary index for fast lookup. */

    std::atomic<uint32_t> next_id_{1};              /**< Thread-safe counter for the lobby IDs. */
    us_timer_t* eviction_timer_ = nullptr;          /**< libuv timer for evicting disconnected users. */
};
