#pragma once
#include <random>
#include <vector>
#include <string>
#include <common/lobby.hpp>

namespace game {

    inline const std::vector<std::string> kReservedBotNames = {
        "GLaDOS", "HAL9000", "Bender", "Wall-E", "R2-D2", "C-3PO",
        "Data", "Lore", "T-800", "Johnny5", "Marvin", "BB-8", "Ultron",
        "Megatron", "Optimus", "Cortana", "Siri", "Alexa", "ChatGPT",
        "Aatrox", "Adventurer", "Alchemist", "Alda", "Alixer", "Amelia", 
        "Andrew", "Angler Angus", "Anita", "Apprentice", "Arthur", 
        "Auction Agents", "Auction Master", "Baker", "Banker", "Bartender", 
        "Bazaar Agent", "Bazaar", "Bea", "Biblio", "Billy Joe", "Bingo", 
        "Blacksmith", "Bobby Joe", "Builder", "Carnival Cowboy", 
        "Carnival Fisherman", "Carnival Leader", "Carnival Pirateman", 
        "Carpenter", "Chantelle", "Christopher", "Clerk Seraphine", 
        "Coach Jackrabbit", "Cole", "Curator", "Derpy", "Diana", "Diaz", 
        "Duke", "Doug", "Dusk", "Elizabeth", "Erihann", "Fann", 
        "Farm Merchant", "Farmer", "Fear Mongerer", "Felix", "Finnegan", 
        "Fishing Merchant", "Fisherman Gerald", "Fisherwoman Enid", "Foxy", 
        "Gavin", "George", "Gladiator", "Guy", "Gwynnie", "Hootie", 
        "Hoppity", "Hub Selector", "Jack", "Jacob", "Jacobus", "Jamie", 
        "Jax", "Jerry", "Jim Bob", "Kat", "Karis", "Leo", "Liam", 
        "Librarian", "Liz", "Lonely Philosopher", "Lucius", "Lukas the Aquarist", 
        "Lumber Jack", "Lumber Merchant", "Lynn", "Mad Redstone Engineer", 
        "Maddox The Slayer", "Malik", "Marco", "Marina", "Maths Enjoyer", 
        "Maxwell", "Mine Merchant", "Mort", "Ophelia", "Oringo", "Ozanne", 
        "Pat", "Paul", "Pig Shop", "Plumber Joe", "Rabbit Bro", "Rabbit Cousin", 
        "Rabbit Daddy", "Rabbit Dog", "Rabbit Granny", "Rabbit Sis", 
        "Rabbit Uncle", "Richard", "Rosetta", "Ryu", "Salesman", "Scoop", 
        "Scorpius", "Security Sloth", "Seymour", "Shania", "Shifty", 
        "Sirius", "SkyBlock Animation", "Smithmonger", "Stella", "Taylor", 
        "Tia The Fairy", "Tom", "Udium", "Vex", "Vincent", "Weaponsmith", 
        "Wizard", "Wool Weaver", "Zog", "Zarina", "Farmhand", "Windmill Operator", 
        "Beth", "Farmer Jon", "Friendly Hiker", "Hungry Hiker", "Hunter Ava", 
        "Jake", "Mason", "Moby", "Shepherd", "Talbot", "Tammy", "Tony", 
        "Treasure Hunter", "Trevor The Trapper", "Gold Forger", "Iron Forger", 
        "Lazy Miner", "Rusty", "Lapis Miner", "Lift Operator", "Redstone Miner", 
        "Rhys", "Walter", "Banker Broadjaw", "Bednom", "Brammor", "Brarnas", 
        "Brynmor", "Bubu", "Bulvar", "Bylma", "Castle Guard", "Cold Enjoyer", 
        "Dalbrek", "Dalir", "Dirt Guy", "Don Expresso", "Dr. Stone", "Dulin", 
        "Emissary Braum", "Emissary Carlton", "Emissary Ceanna", "Emissary Eliza", 
        "Emissary Fraiser", "Emissary Lilith", "Emissary Lissandra", "Emissary Wilson", 
        "Emkam", "Emmor", "Erren", "Fetchur", "Forger", "Fragilis", "Fred", 
        "Geo", "Gimley", "Grandan", "Gwendolyn", "Hornum", "Jotraeline Greatforge", 
        "Lumina", "Marigold", "Old Man Garry", "Puzzler", "Queen Mismyla", 
        "Redros", "Royal Guard", "Royal Resident", "Royal Residents", "Sargwyn", 
        "Scout Plinius", "Scout Scardius", "Sor'Hen", "Silnar", "Station Master", 
        "Tal Ker", "Tarwen", "Thondin", "Thormyr", "Ticket Master", "Tornora", 
        "Bears", "Chunk", "Emissary Sisko", "Gemma", "Geonathan Greatforge", 
        "Kalhuiki Door Guardian", "Keepers", "King Yolkar", "Odawa", 
        "Professor Robot", "Queen's Guards", "Sludge", "Xalx", "Archaeologist", 
        "Bramass Beastslayer", "Grandma Wolf", "Haymitch", "Ike", "Michael", 
        "Rick", "Shaggy", "Spider Tamer", "Alchemage", "Alwin", "An", "Aranya", 
        "Arba", "Arbadak", "Aviar", "Aura", "Arch", "Avorius", "Azax", "Baar", 
        "Barbarian Emissary", "Barbarian Guard", "Barter", "Belanor", "Bromm", 
        "Bruto", "Bruuh", "Captain Ahone", "Carrolyn", "Chief Scorn", "Chihai", 
        "Chak", "Chuk", "Colore", "Corm", "Counsellor", "Cyndarin", "Dean", 
        "Deng", "Desperate Engineer", "Drakuu", "Edelis", "Elle", "Elmar", 
        "Eludore", "Etc", "Ezekiel", "Forast", "Gnyl", "Grelius", "Gris", 
        "Grog", "Hilda", "Igor", "Igrupan", "Jine", "Kaus", "Keran", "Kheharad", 
        "Krevius", "Kutral", "Kuudra Archaeologist", "Kuudra Believer", 
        "Kuudra Gatekeeper", "Kuudra Loremaster", "Lasea", "Lys", "Mage Emissary", 
        "Mage Guard", "Maggie", "Marthos", "Master Tao", "Mazakala", "Mollim", 
        "Nall", "Nuvian", "Odexar", "Odger", "Offea", "Pablo", "Pam", 
        "Piglin Guard", "Plenk", "Pomtair", "Porc", "Prie", "Queen Nyx", 
        "Rescue Recruiter", "Rhanora", "Rollim", "Rulenor", "Scholar Alluin", 
        "Seffea", "Selenar", "Sirih", "Strux", "Suus", "Truu", "Turd", "Udel", 
        "Ugo", "Ulyn", "Undercover Agent", "Uvia", "Velyna", "Vulcan", "Yoink", 
        "Ziri", "Weird Sailor", "Gregory", "Guber", "Lone Adventurer", 
        "Pearl Dealer", "Tyzzo", "Campfire Adept", "Campfire Initiate", "Charlie", 
        "Gustave", "Juliette", "Kelly", "Master Tactician Funk", "Melancholic Viking", 
        "Melody", "Molbert", "Old Shaman Nyko", "Romero", "Ryan", "Vanessa", 
        "Worker Xavier", "Agatha", "Alan", "Albert", "Amaury", "Auryon", 
        "Banker Bonsai", "Boris", "Coral", "David Hunterborough", "Dax", "Hina", 
        "Jaeger", "Kiara", "Kysha", "Loras", "Martin", "Nemo", "Oden", "Pounce", 
        "Rosemary", "Salvage Old Attributes", "Sawyer", "Soul Campfire Adept", 
        "Soul Campfire Initiate", "Swoop", "Talia", "Teddy", "Tilus", "Vaeri", 
        "Captain Baha", "Hattie", "Junker Joel", "Roddy", "Banker Barry", "Daan", 
        "Dirk", "Einary", "Frosty", "Frozen Alex", "Gary", "Generow", "Gulliver", 
        "Helena", "Hendrik", "Maaike", "Mees", "Sherry", "St. Jerry", "Terry", 
        "Adventurer Saul", "Croesus", "Guildford", "Dungeon Hub Selector", 
        "Duncan", "Three Weirdos", "Tomioka", "Trinity", "Winona", "Zodd", 
        "Sam", "Pesthunter Pamela", "Pesthunter Phillip", "Pete", "Maeve", 
        "Spaceman", "Ravenous Rhino", "Pest Wrangler", "Pest Wrangler?", 
        "Vinyl Collector", "Bob", "Alabaster", "Alatar", "Argofay Bughunter", 
        "Argofay Bugshopper", "Argofay Branchstrutter", "Argofay Serialbather", 
        "Argofay Sonfather", "Argofay Threebrother", "Argofay Trafficker", 
        "Argofay Trailblazer", "Argofay Tencounter", "Argofay Treemerger", 
        "Arora", "Ashera", "Barry", "Chef", "Chester", "Chicken", "Cosmo", 
        "Cow", "Cowboy Nick", "Creed", "Cryptosis", "Dackinoru", "Deer", 
        "Detective Amog", "Disinfestor", "Dr. Emmett", "Dr. Hibble", "Dr. Phear", 
        "Dust", "Elise", "Enigma", "Fafnir", "Fairylosopher", "Finplex", 
        "Frankie", "Garlacius", "Grandma", "Gunther", "Harriette", "Hound", 
        "Inverted Sirius", "Jacquelle", "Joey McPizza", "Joliet", "Julian", 
        "Kay", "Kiermet", "Lazarus", "Lonely Ävaeìkx", "Marcia", "Mole", 
        "Motes Grubber", "Mushroom Guy", "Nene", "Phaser", "Porhtal", "Ramero", 
        "Reed", "Ribbit", "Rock", "Roger", "Roy", "Seraphine", "Seskel", 
        "Sheep", "Shifted", "Sick Farmer", "Skylark", "Soma", "Sorcerer Okron", 
        "Stain", "Tel Kar", "Tybalt", "Unbound Explorer", "Unhinged Kloon", 
        "Violetta", "Vreike", "Wizardman", "YoshuayrreJ", "Agent Kapustin", 
        "Agent Komarov", "Agent Kruglov", "Agent Kvasov", "Armorsmith", "Cashier", 
        "Dante", "Dante Goons", "Elle of the Nether", "Game Agent", "Malmar", 
        "Minikloon", "Nitroholic_", "Potato King", "Raffle Box", "Relenter", 
        "Resistance Generals", "Rezzus", "Technoblade", "Technoshop", 
        "The Lost Adventurer", "Warren", "Worker Emma", "Dean", "Garrett", "Hannah", "Allie", 
        "Tucker", "jhon", "Arrodes", "Klein Moretti", "Sauron Einhorn Medici", "Eldyn THE GOAT", 
        "<script>console.log('no XSS!')</script>", "Birdie"
    };
}
