#pragma once
#include <functional>
#include <memory>
#include <string>
#include <string_view>
#include <websocket_context.hpp>

/**
 * @file http.hpp
 * @brief Utility functions for handling the HTTP protocol.
 * * Since uWebSockets uses a non-blocking, event-driven architecture,
 * this file contains crucial helpers to simplify the safe extraction
 * of chunked bodies and the parsing of headers (e.g. Cookies).
 */

namespace http {

/**
 * @brief Asynchronously accumulates an entire chunked HTTP body from uWebSockets.
 * * Since uWebSockets is non-blocking, bodies arrive in one or more `string_view` chunks
 * via the `onData` callback. The `isLast` boolean parameter signals the last chunk.
 * This function buffers the chunks on its own and acts only when the transfer is complete.
 * * @details Implements an `is_alive` memory guard (`std::shared_ptr<bool>`) to handle sudden
 * disconnections. If the client interrupts the transfer, uWS calls `onAborted`. The guard becomes `false`,
 * preventing subsequent `onData` triggers from accessing the now-dangling `res` pointer.
 * * @param res Pointer to the Response object of the current HTTP request. Must remain valid until completion.
 * @param max_bytes Hard cap in bytes to avoid DDoS attacks. If exceeded, returns 413.
 * @param callback The function to invoke, exactly once, with the complete body string (if not aborted).
 * @tag CMN-HTTP-MTH-001
 */
inline void ReadBody(AppResponse* res, size_t max_bytes, std::function<void(const std::string&)> callback) {
    auto is_alive = std::make_shared<bool>(true);
    auto buffer   = std::make_shared<std::string>();

    res->onAborted([is_alive] { *is_alive = false; });

    res->onData([is_alive, buffer, max_bytes, callback = std::move(callback), res](std::string_view chunk, bool isLast) mutable {
        if (!*is_alive) return;

        buffer->append(chunk.data(), chunk.size());

        if (buffer->size() > max_bytes) {
            res->writeStatus("413 Payload Too Large")->end();
            return;
        }

        if (isLast) callback(*buffer);
    });
}

/**
 * @brief Removes ASCII whitespace (spaces, tabs, newlines) from the beginning and end of a string.
 * Being `constexpr`, if evaluated at compile time it generates no overhead.
 * * @param str The view of the original string.
 * @return std::string_view A centred portion of the string free of the outer whitespace. Returns an empty view if composed solely of whitespace.
 * @tag CMN-HTTP-MTH-002
 */
constexpr std::string_view TrimWhitespace(std::string_view str) {
    size_t first = str.find_first_not_of(" \t\r\n");
    if (first == std::string_view::npos) {
        return {};
    }
    size_t last = str.find_last_not_of(" \t\r\n");
    return str.substr(first, (last - first + 1));
}

/**
 * @brief Safely extracts the value of a single cookie from the raw header string.
 * * Iteratively scans the `Cookie` header string (e.g. `session=123; user=abc`),
 * splitting the pairs at the semicolon and looking for the exact key match,
 * cleaning up any whitespace generated by the browser.
 * * @param cookie_header The native HTTP header string containing the cookies.
 * @param target_key The identifying key of the cookie to search for.
 * @return std::optional<std::string> The decoded cookie value, or an empty string if the key does not exist.
 * @tag CMN-HTTP-MTH-003
 */
inline std::optional<std::string> GetCookieValue(std::string_view cookie_header, std::string_view target_key) {
    size_t start = 0;

    while (start < cookie_header.size()) {
        size_t end = cookie_header.find(';', start);

        std::string_view pair = (end == std::string_view::npos)
                                ? cookie_header.substr(start)
                                : cookie_header.substr(start, end - start);

        // Split the pair into Key and Value
        size_t eq_pos = pair.find('=');
        if (eq_pos != std::string_view::npos) {
            std::string_view key = TrimWhitespace(pair.substr(0, eq_pos));

            if (key == target_key) {
                return std::string(TrimWhitespace(pair.substr(eq_pos + 1)));
            }
        }

        if (end == std::string_view::npos) {
            break;
        }

        start = end + 1;
    }

    return "";
}

/**
 * @brief Resolve the originating client IP for rate-limiting / logging.
 *
 * When `trust_proxy` is true the server is assumed to sit behind a single
 * reverse proxy (e.g. Traefik) that appends the peer address to
 * `X-Forwarded-For`. In that case the **right-most** entry is the address the
 * proxy actually observed and is therefore the trustworthy client IP; entries to
 * its left are client-supplied and spoofable. When `trust_proxy` is false, or the
 * header is absent, the socket peer address is used.
 *
 * @param res Response, used for the socket peer address fallback.
 * @param req Request, source of the `X-Forwarded-For` header.
 * @param trust_proxy Whether to honour `X-Forwarded-For` (set behind a proxy).
 * @return std::string The resolved client IP (may be empty if unavailable).
 * @tag CMN-HTTP-MTH-004
 */
inline std::string GetClientIp(AppResponse* res, AppRequest* req, bool trust_proxy) {
    if (trust_proxy) {
        std::string_view xff = req->getHeader("x-forwarded-for");
        if (!xff.empty()) {
            size_t comma = xff.rfind(',');
            std::string_view last = (comma == std::string_view::npos)
                                        ? xff
                                        : xff.substr(comma + 1);
            return std::string(TrimWhitespace(last));
        }
    }
    return std::string(res->getRemoteAddressAsText());
}

}
