export const ClientAction = {
    LobbyList: "lobby_list",
    LobbyCreate: "lobby_create",
    LobbyJoin: "lobby_join",
    LobbyLeave: "lobby_leave",
    LobbyInvite: "lobby_invite",
    LobbySetRuleset: "lobby_set_ruleset",
    LobbySetSkin: "lobby_set_skin",
    Ready: "ready",
    PlayCard: "play_card",
    DrawCard: "draw_card",
    CallUno: "call_uno",
    ChallengeUno: "challenge_uno",
    ChallengePlusFour: "challenge_plus_four",
    ChooseColor: "choose_color",
    AckGameOver: "ack_game_over",
    StorePurchase: "store_purchase",
    InventoryRequest: "inventory_request",
    ChatSend: "chat_send",
} as const;

export const ServerAction = {
    SyncData: "sync_data",
    Error: "error",
    LobbyList: "lobby_list",
    LobbyUpdated: "lobby_updated",
    LobbyJoined: "lobby_joined",
    LobbyLeft: "lobby_left",
    InviteCreated: "invite_created",
    PlayerJoined: "player_joined",
    PlayerLeft: "player_left",
    PlayerReady: "player_ready",
    GameStarting: "game_starting",
    RulesetSync: "ruleset_sync",
    StateUpdate: "state_update",
    CardRejected: "card_rejected",
    CardDrawn: "card_drawn",
    TurnChanged: "turn_changed",
    ColorChanged: "color_changed",
    UnoCallSuccess: "uno_call_success",
    UnoCallFailed: "uno_call_failed",
    UnoChallenged: "uno_challenged",
    CardPlayed: "card_played",
    PlayerDrewCard: "player_drew_card",
    SkipApplied: "skip_applied",
    ReverseApplied: "reverse_applied",
    DrawStackApplied: "draw_stack_applied",
    GameOver: "game_over",
    RoundOver: "round_over",
    InventorySync: "inventory_sync",
    PurchaseConfirmed: "purchase_confirmed",
    PurchaseFailed: "purchase_failed",
    ChatMessage: "chat_message",
} as const;

export type ClientActionType = (typeof ClientAction)[keyof typeof ClientAction];
export type ServerActionType = (typeof ServerAction)[keyof typeof ServerAction];
